version: '3.8'

services:
  postgres:
    image: 'postgres:16'
    container_name: whatsappp_container
    environment:
      POSTGRES_DB: whatsappp_db
      POSTGRES_USER: ridoy
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  pg_data:

networks:
  postgres-network:
    driver: bridge